// Environment variables
export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
export const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';
export const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';
export const NASA_API_KEY = process.env.NEXT_PUBLIC_NASA_API_KEY || '';

// Constants
export const PLANETS = [
  {
    id: 1,
    name: 'Mercury',
    icon: '☿️',
    description: 'The smallest and closest planet to the Sun',
    diameter: '3,832 km',
    distanceFromSun: '57.9 million km',
    rotationPeriod: '58.6 days',
    revolutionPeriod: '88 days',
    gravity: '3.7 m/s²',
    moons: 0,
    atmosphere: 'Virtually none',
    color: '#8C7853',
  },
  {
    id: 2,
    name: 'Venus',
    icon: '♀️',
    description: 'The hottest planet with a thick toxic atmosphere',
    diameter: '12,104 km',
    distanceFromSun: '108.2 million km',
    rotationPeriod: '243 days',
    revolutionPeriod: '225 days',
    gravity: '8.87 m/s²',
    moons: 0,
    atmosphere: 'Carbon dioxide with sulfuric acid clouds',
    color: '#FFC649',
  },
  {
    id: 3,
    name: 'Earth',
    icon: '🌍',
    description: 'Our home planet, the only known world with life',
    diameter: '12,742 km',
    distanceFromSun: '149.6 million km',
    rotationPeriod: '23.9 hours',
    revolutionPeriod: '365.25 days',
    gravity: '9.81 m/s²',
    moons: 1,
    atmosphere: 'Nitrogen and oxygen',
    color: '#4A90E2',
  },
  {
    id: 4,
    name: 'Mars',
    icon: '♂️',
    description: 'The red planet with signs of ancient water',
    diameter: '6,779 km',
    distanceFromSun: '227.9 million km',
    rotationPeriod: '24.6 hours',
    revolutionPeriod: '687 days',
    gravity: '3.71 m/s²',
    moons: 2,
    atmosphere: 'Carbon dioxide',
    color: '#E27B58',
  },
  {
    id: 5,
    name: 'Jupiter',
    icon: '♃',
    description: 'The gas giant with a great red spot storm',
    diameter: '139,820 km',
    distanceFromSun: '778.5 million km',
    rotationPeriod: '9.9 hours',
    revolutionPeriod: '12 years',
    gravity: '24.79 m/s²',
    moons: 95,
    atmosphere: 'Hydrogen and helium',
    color: '#C88B3A',
  },
  {
    id: 6,
    name: 'Saturn',
    icon: '♄',
    description: 'The ringed planet with magnificent rings',
    diameter: '116,460 km',
    distanceFromSun: '1.4 billion km',
    rotationPeriod: '10.7 hours',
    revolutionPeriod: '29 years',
    gravity: '10.44 m/s²',
    moons: 146,
    atmosphere: 'Hydrogen and helium',
    color: '#FAD5A5',
  },
  {
    id: 7,
    name: 'Uranus',
    icon: '♅',
    description: 'The ice giant that rotates on its side',
    diameter: '50,724 km',
    distanceFromSun: '2.9 billion km',
    rotationPeriod: '17.2 hours',
    revolutionPeriod: '84 years',
    gravity: '8.87 m/s²',
    moons: 28,
    atmosphere: 'Methane, ammonia, and water',
    color: '#4FD0E7',
  },
  {
    id: 8,
    name: 'Neptune',
    icon: '♆',
    description: 'The windy blue planet at the edge of our solar system',
    diameter: '49,244 km',
    distanceFromSun: '4.5 billion km',
    rotationPeriod: '16.1 hours',
    revolutionPeriod: '165 years',
    gravity: '11.15 m/s²',
    moons: 16,
    atmosphere: 'Methane gives it blue color',
    color: '#4166F5',
  },
];

export const QUIZ_CATEGORIES = [
  { id: 1, name: 'Solar System', icon: '🪐', color: 'from-blue-500 to-purple-500' },
  { id: 2, name: 'Eclipses', icon: '🌑', color: 'from-purple-500 to-pink-500' },
  { id: 3, name: 'Seasons', icon: '🌍', color: 'from-green-500 to-blue-500' },
  { id: 4, name: 'Moon Phases', icon: '🌙', color: 'from-yellow-500 to-orange-500' },
  { id: 5, name: 'General Astronomy', icon: '⭐', color: 'from-indigo-500 to-cyan-500' },
];

export const LEARNING_MODULES = [
  { id: 1, title: 'Solar System Explorer', icon: '🪐', description: 'Explore all 8 planets and learn their characteristics' },
  { id: 2, title: 'Eclipses Simulator', icon: '🌑', description: 'Understand solar and lunar eclipses with interactive simulations' },
  { id: 3, title: 'Seasons Explained', icon: '🌍', description: 'Learn why seasons change and how Earth\'s tilt affects climate' },
  { id: 4, title: 'Moon Phases', icon: '🌙', description: 'Track the lunar cycle and understand moon phases' },
  { id: 5, title: 'Ocean Tides', icon: '🌊', description: 'Discover how the Moon controls our oceans' },
  { id: 6, title: 'ISRO Missions', icon: '🇮🇳', description: 'Learn about India\'s space missions and achievements' },
];
